"""initial schema

Revision ID: 37ba1cfe8d27
Revises: 
Create Date: 2026-07-28 10:02:41.263107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '37ba1cfe8d27'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_type', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('bank_name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("account_type IN ('private', 'company')", name='ck_accounts_account_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.CheckConstraint("type IN ('income', 'expense', 'transfer')", name='ck_categories_type'),
    sa.CheckConstraint('score BETWEEN 0 AND 100', name='ck_categories_score_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fixed_costs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('expected_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('frequency', sa.Text(), nullable=False),
    sa.CheckConstraint("frequency IN ('monthly', 'quarterly', 'yearly')", name='ck_fixed_costs_frequency'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('report_type', sa.Text(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('content_html', sa.Text(), nullable=False),
    sa.Column('delivery_status', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("delivery_status IN ('pending', 'sent', 'failed')", name='ck_reports_delivery_status'),
    sa.CheckConstraint("report_type IN ('weekly', 'monthly')", name='ck_reports_report_type'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('statements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('drive_file_id', sa.Text(), nullable=False),
    sa.Column('file_name', sa.Text(), nullable=False),
    sa.Column('checksum', sa.Text(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('closing_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'verified', 'failed', 'processed')", name='ck_statements_status'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'drive_file_id', name='uq_statements_account_drive_file')
    )
    op.create_table('investment_recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('surplus_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('allocation_proposal', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('statement_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('txn_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('counterparty', sa.Text(), nullable=True),
    sa.Column('running_balance', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('category_source', sa.Text(), nullable=True),
    sa.Column('category_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('review_status', sa.Text(), nullable=False),
    sa.CheckConstraint("category_source IN ('rule', 'llm', 'manual')", name='ck_transactions_category_source'),
    sa.CheckConstraint("review_status IN ('auto', 'needs_review', 'confirmed')", name='ck_transactions_review_status'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['statement_id'], ['statements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('investment_recommendations')
    op.drop_table('statements')
    op.drop_table('reports')
    op.drop_table('fixed_costs')
    op.drop_table('categories')
    op.drop_table('accounts')
    # ### end Alembic commands ###
