"""add unique constraint on accounts.account_type

Revision ID: 9d0d806b066e
Revises: 37ba1cfe8d27
Create Date: 2026-07-28 14:40:20.010794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d0d806b066e'
down_revision: Union[str, Sequence[str], None] = '37ba1cfe8d27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_accounts_account_type', 'accounts', ['account_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_accounts_account_type', 'accounts', type_='unique')
    # ### end Alembic commands ###
